/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DailyGMInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PROTOCOL_FEE"
      | "RESTORE_FEE"
      | "brokenStreak"
      | "currentStreak"
      | "gm"
      | "lastGMTime"
      | "longestStreak"
      | "owner"
      | "renounceOwnership"
      | "restoreStreak"
      | "totalGMs"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GM" | "OwnershipTransferred" | "StreakRestored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESTORE_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "brokenStreak",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentStreak",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "gm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastGMTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "longestStreak",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "restoreStreak",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalGMs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESTORE_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "brokenStreak",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentStreak",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastGMTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "longestStreak",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restoreStreak",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalGMs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace GMEvent {
  export type InputTuple = [
    user: AddressLike,
    streak: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, streak: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    streak: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreakRestoredEvent {
  export type InputTuple = [
    user: AddressLike,
    streak: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, streak: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    streak: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DailyGM extends BaseContract {
  connect(runner?: ContractRunner | null): DailyGM;
  waitForDeployment(): Promise<this>;

  interface: DailyGMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PROTOCOL_FEE: TypedContractMethod<[], [bigint], "view">;

  RESTORE_FEE: TypedContractMethod<[], [bigint], "view">;

  brokenStreak: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  currentStreak: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  gm: TypedContractMethod<[], [void], "payable">;

  lastGMTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  longestStreak: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  restoreStreak: TypedContractMethod<[], [void], "payable">;

  totalGMs: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PROTOCOL_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESTORE_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "brokenStreak"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentStreak"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "gm"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "lastGMTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "longestStreak"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "restoreStreak"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "totalGMs"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "GM"
  ): TypedContractEvent<
    GMEvent.InputTuple,
    GMEvent.OutputTuple,
    GMEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StreakRestored"
  ): TypedContractEvent<
    StreakRestoredEvent.InputTuple,
    StreakRestoredEvent.OutputTuple,
    StreakRestoredEvent.OutputObject
  >;

  filters: {
    "GM(address,uint256,uint256)": TypedContractEvent<
      GMEvent.InputTuple,
      GMEvent.OutputTuple,
      GMEvent.OutputObject
    >;
    GM: TypedContractEvent<
      GMEvent.InputTuple,
      GMEvent.OutputTuple,
      GMEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StreakRestored(address,uint256,uint256)": TypedContractEvent<
      StreakRestoredEvent.InputTuple,
      StreakRestoredEvent.OutputTuple,
      StreakRestoredEvent.OutputObject
    >;
    StreakRestored: TypedContractEvent<
      StreakRestoredEvent.InputTuple,
      StreakRestoredEvent.OutputTuple,
      StreakRestoredEvent.OutputObject
    >;
  };
}
