-- Create table for storing raw GM events
create table if not exists public.gm_events (
  id bigint generated by default as identity primary key,
  user_address text not null,
  streak int not null,
  block_number bigint not null,
  block_timestamp bigint not null,
  tx_hash text not null unique,
  event_type text not null default 'gm', -- 'gm' or 'restore'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create table for aggregated user stats (Leaderboard + Analytics)
create table if not exists public.users (
  address text primary key,
  
  -- Public Stats (Leaderboard/Profile)
  current_streak int not null default 0,
  longest_streak int not null default 0,
  total_gms int not null default 0,
  last_gm timestamptz,
  first_gm_date timestamptz default timezone('utc'::text, now()), -- Account Age
  
  -- Private/Gated Stats (Internal Analytics)
  broken_streaks int not null default 0,
  restores_used int not null default 0,
  total_fees_paid numeric not null default 0, -- Stored as ETH amount (e.g. 0.05)
  
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.gm_events enable row level security;
alter table public.users enable row level security;

-- Create a secure public view for the leaderboard exposing ONLY public fields
create or replace view public.public_leaderboard as
select 
  address, 
  current_streak, 
  longest_streak, 
  total_gms, 
  last_gm, 
  first_gm_date
from public.users;

-- Grant access to the view
grant select on public.public_leaderboard to anon, authenticated;

-- Revoke public access to the raw users table entirely
create policy "Restrict users table reading to service role only"
on public.users for select 
using (auth.role() = 'service_role');

-- Re-allow anonymous read access on gm_events (Live Feed is public)
create policy "Allow public read access on gm_events"
on public.gm_events for select using (true);

-- Index for faster leaderboard queries
create index if not exists idx_users_streak on public.users (current_streak desc);
create index if not exists idx_events_block_number on public.gm_events (block_number desc);
