const fs = require('fs');

const file = fs.readdirSync('out/build-info')[0];
const raw = fs.readFileSync('out/build-info/' + file, 'utf8');

// The build-info file generated by foundry has {id, source_id_to_path, language, input, output}
// BaseScan wants the exact 'input' object (which contains language, sources, and settings)
const data = JSON.parse(raw);

const standardJson = data.input;

fs.writeFileSync('DailyGM-Standard-Json.json', JSON.stringify(standardJson));
console.log('Successfully wrote exact ABI encoding to DailyGM-Standard-Json.json');
