const fs = require('fs');
const solc = require('solc');

const sourceCode = fs.readFileSync('FlatDailyGM.sol', 'utf8');

const input = {
    language: 'Solidity',
    sources: {
        'FlatDailyGM.sol': {
            content: sourceCode
        }
    },
    settings: {
        viaIR: true,
        evmVersion: 'cancun',
        optimizer: {
            enabled: true,
            runs: 200
        },
        outputSelection: {
            '*': {
                '*': ['*']
            }
        }
    }
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));
const bytecode = output.contracts['FlatDailyGM.sol'].DailyGM.evm.bytecode.object;

console.log("Generated Bytecode Prefix:");
console.log(bytecode.substring(0, 150));
console.log("\nIf it contains '5f5ffd', viaIR is the solution!");
